config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true
    validates :content, length: { minimum: 1 }  # 値が「1文字以上」であれば有効
    validates :content, length: { maximum: 140 }  # 値が「140文字以下」であれば有効
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]
  
  def index
    @tweets = Tweet.all
  end
  
  def new
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end

  def create
    @tweet = Tweet.new(tweets_params)
    if @tweet.save
      # 一覧へ遷移。noticeのメッセージ表示
      redirect_to tweets_path, notice: "つぶやきました！"
    else
      # 入力フォームを再描画
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    @tweet.update(tweets_params)
    if @tweet.save
      # 一覧へ遷移。noticeのメッセージ表示
      redirect_to tweets_path, notice: "つぶやきました！"
    else
      # 編集フォームを再描画
      render 'edit'
    end
  end
  
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end
  
  private
    def tweets_params
      params.require(:tweet).permit(:content)
    end
    
    # idをキーとして値を取得するメソッド
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to "トップページ", root_path, class: "navbar-brand" %>
     </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "つぶやく", new_tweet_path %></li>
    <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
    <li><%= link_to "つぶやき一覧", tweets_path %></li>
  </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

<%= yield %>

<footer>
  <p>© Tetsu.</p>
</footer>

</body>
</html>

app/views/top/index.html.erb
<section>
<div class="row">
  <h1>本音をつぶやいても炎上しません。</h1>
  <p>
    胸の内にある本音つぶやきましょう。<br>
    ここでつぶやいても決して炎上しません。
  </p>
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="twitter-image">
      <img src="<%= asset_path "twitter.png" %>">
    </div>
      <%= link_to "早速つぶやいてみる", new_tweet_path, class: 'tweet-btn btn btn-default' %>
    </div>
</div>
      </div>
</section>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <%# バリデーションエラーの件数を表示します。 %>
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <%# @tweet.errorsは@tweetをバリデーションした際のエラー情報です。 %>
      <%# full_messagesは複数のエラーメッセージを表します。 %>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "一覧画面にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>

<%= form_for(@tweet) do |f| %>
  <%# `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 %>
  <%= f.hidden_field :content %>

  <%# @tweet.contentとすることで、表示用の値を画面に出力しています。 %>
  <p>本文:<%= @tweet.content %></p>
  <%= f.submit "つぶやく", class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back', class: 'btn btn-primary btn-block' %>
<% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<p id="notice"><%= notice %></p>

<h2>つぶやきを編集</h2>

<%= render 'form' %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p><%= notice %></p>
<h1>つぶやき一覧</h1>
<%= link_to "投稿する", new_tweet_path, class: 'btn btn-default' %>
<% @tweets.each do |tweet| %>
<div class="row">
  <p><%= tweet.content %></p>
  <%= link_to "編集する", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success' %>
  <%= link_to "削除する", tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger' %>
</div>
<% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
      <p id="notice"><%= notice %></p>

<h2>つぶやく</h2>

<%= render 'form' %>
  </div>
</div>